/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#include "CurrentRate.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
value_6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using NonNegativeReal,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_valueBase_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_valueBase_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_value_constr_6 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_value_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_valueBase_value2enum_2[] = {
	{ 0,	9,	"unlimited" },
	{ 1,	14,	"bytesPerSecond" },
	{ 2,	17,	"messagesPerSecond" }
};
static const unsigned int asn_MAP_valueBase_enum2value_2[] = {
	1,	/* bytesPerSecond(1) */
	2,	/* messagesPerSecond(2) */
	0	/* unlimited(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_valueBase_specs_2 = {
	asn_MAP_valueBase_value2enum_2,	/* "tag" => N; sorted by tag */
	asn_MAP_valueBase_enum2value_2,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_valueBase_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_valueBase_2 = {
	"valueBase",
	"valueBase",
	&asn_OP_NativeEnumerated,
	asn_DEF_valueBase_tags_2,
	sizeof(asn_DEF_valueBase_tags_2)
		/sizeof(asn_DEF_valueBase_tags_2[0]) - 1, /* 1 */
	asn_DEF_valueBase_tags_2,	/* Same as above */
	sizeof(asn_DEF_valueBase_tags_2)
		/sizeof(asn_DEF_valueBase_tags_2[0]), /* 2 */
	{ &asn_OER_type_valueBase_constr_2, &asn_PER_type_valueBase_constr_2, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_valueBase_specs_2	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_value_specs_6 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_value_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_value_6 = {
	"value",
	"value",
	&asn_OP_NativeReal,
	asn_DEF_value_tags_6,
	sizeof(asn_DEF_value_tags_6)
		/sizeof(asn_DEF_value_tags_6[0]) - 1, /* 1 */
	asn_DEF_value_tags_6,	/* Same as above */
	sizeof(asn_DEF_value_tags_6)
		/sizeof(asn_DEF_value_tags_6[0]), /* 2 */
	{ &asn_OER_type_value_constr_6, &asn_PER_type_value_constr_6, value_6_constraint },
	0, 0,	/* No members */
	&asn_SPC_value_specs_6	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_CurrentRate_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentRate, valueBase),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_valueBase_2,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"valueBase"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct CurrentRate, value),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NonNegativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"value"
		},
};
static const ber_tlv_tag_t asn_DEF_CurrentRate_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_CurrentRate_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* valueBase */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* value */
};
asn_SEQUENCE_specifics_t asn_SPC_CurrentRate_specs_1 = {
	sizeof(struct CurrentRate),
	offsetof(struct CurrentRate, _asn_ctx),
	asn_MAP_CurrentRate_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_CurrentRate = {
	"CurrentRate",
	"CurrentRate",
	&asn_OP_SEQUENCE,
	asn_DEF_CurrentRate_tags_1,
	sizeof(asn_DEF_CurrentRate_tags_1)
		/sizeof(asn_DEF_CurrentRate_tags_1[0]), /* 1 */
	asn_DEF_CurrentRate_tags_1,	/* Same as above */
	sizeof(asn_DEF_CurrentRate_tags_1)
		/sizeof(asn_DEF_CurrentRate_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_CurrentRate_1,
	2,	/* Elements count */
	&asn_SPC_CurrentRate_specs_1	/* Additional specs */
};

