/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#ifndef	_CurrentRate_H_
#define	_CurrentRate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeEnumerated.h>
#include "NonNegativeReal.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum valueBase {
	valueBase_unlimited	= 0,
	valueBase_bytesPerSecond	= 1,
	valueBase_messagesPerSecond	= 2
} e_valueBase;

/* CurrentRate */
typedef struct CurrentRate {
	long	 valueBase;
	NonNegativeReal_t	 value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CurrentRate_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_valueBase_2;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_value_6;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_CurrentRate;
extern asn_SEQUENCE_specifics_t asn_SPC_CurrentRate_specs_1;
extern asn_TYPE_member_t asn_MBR_CurrentRate_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _CurrentRate_H_ */
#include <asn_internal.h>
