/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#include "Start.h"

static int
connectRate_14_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
connectTimeout_15_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
channelLifetime_16_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
channelBandwidthUpstream_17_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
channelBandwidthDownstream_18_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
duration_23_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
delaySend_24_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static int
messageRate_28_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using PositiveReal,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_connectRate_constr_14 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_connectRate_constr_14 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_connectTimeout_constr_15 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_connectTimeout_constr_15 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_channelLifetime_constr_16 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_channelLifetime_constr_16 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_channelBandwidthUpstream_constr_17 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_channelBandwidthUpstream_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_channelBandwidthDownstream_constr_18 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_channelBandwidthDownstream_constr_18 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_listenMode_constr_20 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_listenMode_constr_20 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_duration_constr_23 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_duration_constr_23 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_delaySend_constr_24 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_delaySend_constr_24 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_messageRate_constr_28 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_messageRate_constr_28 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_NativeReal_specifics_t asn_SPC_connectRate_specs_14 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_connectRate_tags_14[] = {
	(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connectRate_14 = {
	"connectRate",
	"connectRate",
	&asn_OP_NativeReal,
	asn_DEF_connectRate_tags_14,
	sizeof(asn_DEF_connectRate_tags_14)
		/sizeof(asn_DEF_connectRate_tags_14[0]) - 1, /* 1 */
	asn_DEF_connectRate_tags_14,	/* Same as above */
	sizeof(asn_DEF_connectRate_tags_14)
		/sizeof(asn_DEF_connectRate_tags_14[0]), /* 2 */
	{ &asn_OER_type_connectRate_constr_14, &asn_PER_type_connectRate_constr_14, connectRate_14_constraint },
	0, 0,	/* No members */
	&asn_SPC_connectRate_specs_14	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_connectTimeout_specs_15 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_connectTimeout_tags_15[] = {
	(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_connectTimeout_15 = {
	"connectTimeout",
	"connectTimeout",
	&asn_OP_NativeReal,
	asn_DEF_connectTimeout_tags_15,
	sizeof(asn_DEF_connectTimeout_tags_15)
		/sizeof(asn_DEF_connectTimeout_tags_15[0]) - 1, /* 1 */
	asn_DEF_connectTimeout_tags_15,	/* Same as above */
	sizeof(asn_DEF_connectTimeout_tags_15)
		/sizeof(asn_DEF_connectTimeout_tags_15[0]), /* 2 */
	{ &asn_OER_type_connectTimeout_constr_15, &asn_PER_type_connectTimeout_constr_15, connectTimeout_15_constraint },
	0, 0,	/* No members */
	&asn_SPC_connectTimeout_specs_15	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_channelLifetime_specs_16 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_channelLifetime_tags_16[] = {
	(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_channelLifetime_16 = {
	"channelLifetime",
	"channelLifetime",
	&asn_OP_NativeReal,
	asn_DEF_channelLifetime_tags_16,
	sizeof(asn_DEF_channelLifetime_tags_16)
		/sizeof(asn_DEF_channelLifetime_tags_16[0]) - 1, /* 1 */
	asn_DEF_channelLifetime_tags_16,	/* Same as above */
	sizeof(asn_DEF_channelLifetime_tags_16)
		/sizeof(asn_DEF_channelLifetime_tags_16[0]), /* 2 */
	{ &asn_OER_type_channelLifetime_constr_16, &asn_PER_type_channelLifetime_constr_16, channelLifetime_16_constraint },
	0, 0,	/* No members */
	&asn_SPC_channelLifetime_specs_16	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_channelBandwidthUpstream_specs_17 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_channelBandwidthUpstream_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_channelBandwidthUpstream_17 = {
	"channelBandwidthUpstream",
	"channelBandwidthUpstream",
	&asn_OP_NativeReal,
	asn_DEF_channelBandwidthUpstream_tags_17,
	sizeof(asn_DEF_channelBandwidthUpstream_tags_17)
		/sizeof(asn_DEF_channelBandwidthUpstream_tags_17[0]) - 1, /* 1 */
	asn_DEF_channelBandwidthUpstream_tags_17,	/* Same as above */
	sizeof(asn_DEF_channelBandwidthUpstream_tags_17)
		/sizeof(asn_DEF_channelBandwidthUpstream_tags_17[0]), /* 2 */
	{ &asn_OER_type_channelBandwidthUpstream_constr_17, &asn_PER_type_channelBandwidthUpstream_constr_17, channelBandwidthUpstream_17_constraint },
	0, 0,	/* No members */
	&asn_SPC_channelBandwidthUpstream_specs_17	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_channelBandwidthDownstream_specs_18 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_channelBandwidthDownstream_tags_18[] = {
	(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_channelBandwidthDownstream_18 = {
	"channelBandwidthDownstream",
	"channelBandwidthDownstream",
	&asn_OP_NativeReal,
	asn_DEF_channelBandwidthDownstream_tags_18,
	sizeof(asn_DEF_channelBandwidthDownstream_tags_18)
		/sizeof(asn_DEF_channelBandwidthDownstream_tags_18[0]) - 1, /* 1 */
	asn_DEF_channelBandwidthDownstream_tags_18,	/* Same as above */
	sizeof(asn_DEF_channelBandwidthDownstream_tags_18)
		/sizeof(asn_DEF_channelBandwidthDownstream_tags_18[0]), /* 2 */
	{ &asn_OER_type_channelBandwidthDownstream_constr_18, &asn_PER_type_channelBandwidthDownstream_constr_18, channelBandwidthDownstream_18_constraint },
	0, 0,	/* No members */
	&asn_SPC_channelBandwidthDownstream_specs_18	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_listenMode_value2enum_20[] = {
	{ 0,	6,	"silent" },
	{ 1,	6,	"active" }
};
static const unsigned int asn_MAP_listenMode_enum2value_20[] = {
	1,	/* active(1) */
	0	/* silent(0) */
};
static const asn_INTEGER_specifics_t asn_SPC_listenMode_specs_20 = {
	asn_MAP_listenMode_value2enum_20,	/* "tag" => N; sorted by tag */
	asn_MAP_listenMode_enum2value_20,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_listenMode_tags_20[] = {
	(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_listenMode_20 = {
	"listenMode",
	"listenMode",
	&asn_OP_NativeEnumerated,
	asn_DEF_listenMode_tags_20,
	sizeof(asn_DEF_listenMode_tags_20)
		/sizeof(asn_DEF_listenMode_tags_20[0]) - 1, /* 1 */
	asn_DEF_listenMode_tags_20,	/* Same as above */
	sizeof(asn_DEF_listenMode_tags_20)
		/sizeof(asn_DEF_listenMode_tags_20[0]), /* 2 */
	{ &asn_OER_type_listenMode_constr_20, &asn_PER_type_listenMode_constr_20, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_listenMode_specs_20	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_duration_specs_23 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_duration_tags_23[] = {
	(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_duration_23 = {
	"duration",
	"duration",
	&asn_OP_NativeReal,
	asn_DEF_duration_tags_23,
	sizeof(asn_DEF_duration_tags_23)
		/sizeof(asn_DEF_duration_tags_23[0]) - 1, /* 1 */
	asn_DEF_duration_tags_23,	/* Same as above */
	sizeof(asn_DEF_duration_tags_23)
		/sizeof(asn_DEF_duration_tags_23[0]), /* 2 */
	{ &asn_OER_type_duration_constr_23, &asn_PER_type_duration_constr_23, duration_23_constraint },
	0, 0,	/* No members */
	&asn_SPC_duration_specs_23	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_delaySend_specs_24 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_delaySend_tags_24[] = {
	(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_delaySend_24 = {
	"delaySend",
	"delaySend",
	&asn_OP_NativeReal,
	asn_DEF_delaySend_tags_24,
	sizeof(asn_DEF_delaySend_tags_24)
		/sizeof(asn_DEF_delaySend_tags_24[0]) - 1, /* 1 */
	asn_DEF_delaySend_tags_24,	/* Same as above */
	sizeof(asn_DEF_delaySend_tags_24)
		/sizeof(asn_DEF_delaySend_tags_24[0]), /* 2 */
	{ &asn_OER_type_delaySend_constr_24, &asn_PER_type_delaySend_constr_24, delaySend_24_constraint },
	0, 0,	/* No members */
	&asn_SPC_delaySend_specs_24	/* Additional specs */
};

static const asn_NativeReal_specifics_t asn_SPC_messageRate_specs_28 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_messageRate_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageRate_28 = {
	"messageRate",
	"messageRate",
	&asn_OP_NativeReal,
	asn_DEF_messageRate_tags_28,
	sizeof(asn_DEF_messageRate_tags_28)
		/sizeof(asn_DEF_messageRate_tags_28[0]) - 1, /* 1 */
	asn_DEF_messageRate_tags_28,	/* Same as above */
	sizeof(asn_DEF_messageRate_tags_28)
		/sizeof(asn_DEF_messageRate_tags_28[0]), /* 2 */
	{ &asn_OER_type_messageRate_constr_28, &asn_PER_type_messageRate_constr_28, messageRate_28_constraint },
	0, 0,	/* No members */
	&asn_SPC_messageRate_specs_28	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_Start_1[] = {
	{ ATF_POINTER, 37, offsetof(struct Start, target),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_URL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"target"
		},
	{ ATF_POINTER, 36, offsetof(struct Start, nagle),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"nagle"
		},
	{ ATF_POINTER, 35, offsetof(struct Start, rcvbuf),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rcvbuf"
		},
	{ ATF_POINTER, 34, offsetof(struct Start, sndbuf),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sndbuf"
		},
	{ ATF_POINTER, 33, offsetof(struct Start, writeCombine),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"writeCombine"
		},
	{ ATF_POINTER, 32, offsetof(struct Start, workers),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"workers"
		},
	{ ATF_POINTER, 31, offsetof(struct Start, ws),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ws"
		},
	{ ATF_POINTER, 30, offsetof(struct Start, ssl),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ssl"
		},
	{ ATF_POINTER, 29, offsetof(struct Start, sslCert),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sslCert"
		},
	{ ATF_POINTER, 28, offsetof(struct Start, sslKey),
		(ASN_TAG_CLASS_CONTEXT | (9 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"sslKey"
		},
	{ ATF_POINTER, 27, offsetof(struct Start, header),
		(ASN_TAG_CLASS_CONTEXT | (10 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"header"
		},
	{ ATF_POINTER, 26, offsetof(struct Start, connections),
		(ASN_TAG_CLASS_CONTEXT | (11 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"connections"
		},
	{ ATF_POINTER, 25, offsetof(struct Start, connectRate),
		(ASN_TAG_CLASS_CONTEXT | (12 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"connectRate"
		},
	{ ATF_POINTER, 24, offsetof(struct Start, connectTimeout),
		(ASN_TAG_CLASS_CONTEXT | (13 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"connectTimeout"
		},
	{ ATF_POINTER, 23, offsetof(struct Start, channelLifetime),
		(ASN_TAG_CLASS_CONTEXT | (14 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelLifetime"
		},
	{ ATF_POINTER, 22, offsetof(struct Start, channelBandwidthUpstream),
		(ASN_TAG_CLASS_CONTEXT | (15 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelBandwidthUpstream"
		},
	{ ATF_POINTER, 21, offsetof(struct Start, channelBandwidthDownstream),
		(ASN_TAG_CLASS_CONTEXT | (16 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"channelBandwidthDownstream"
		},
	{ ATF_POINTER, 20, offsetof(struct Start, listenPort),
		(ASN_TAG_CLASS_CONTEXT | (17 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TcpPort,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listenPort"
		},
	{ ATF_POINTER, 19, offsetof(struct Start, listenMode),
		(ASN_TAG_CLASS_CONTEXT | (18 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_listenMode_20,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"listenMode"
		},
	{ ATF_POINTER, 18, offsetof(struct Start, duration),
		(ASN_TAG_CLASS_CONTEXT | (19 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"duration"
		},
	{ ATF_POINTER, 17, offsetof(struct Start, delaySend),
		(ASN_TAG_CLASS_CONTEXT | (20 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"delaySend"
		},
	{ ATF_POINTER, 16, offsetof(struct Start, firstMessage),
		(ASN_TAG_CLASS_CONTEXT | (21 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"firstMessage"
		},
	{ ATF_POINTER, 15, offsetof(struct Start, message),
		(ASN_TAG_CLASS_CONTEXT | (22 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"message"
		},
	{ ATF_POINTER, 14, offsetof(struct Start, messageFile),
		(ASN_TAG_CLASS_CONTEXT | (23 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageFile"
		},
	{ ATF_POINTER, 13, offsetof(struct Start, messageRate),
		(ASN_TAG_CLASS_CONTEXT | (24 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageRate"
		},
	{ ATF_POINTER, 12, offsetof(struct Start, messageStop),
		(ASN_TAG_CLASS_CONTEXT | (25 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageStop"
		},
	{ ATF_POINTER, 11, offsetof(struct Start, latencyConnect),
		(ASN_TAG_CLASS_CONTEXT | (26 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"latencyConnect"
		},
	{ ATF_POINTER, 10, offsetof(struct Start, latencyFirstByte),
		(ASN_TAG_CLASS_CONTEXT | (27 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"latencyFirstByte"
		},
	{ ATF_POINTER, 9, offsetof(struct Start, latencyMarker),
		(ASN_TAG_CLASS_CONTEXT | (28 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"latencyMarker"
		},
	{ ATF_POINTER, 8, offsetof(struct Start, latencyMarkerSkip),
		(ASN_TAG_CLASS_CONTEXT | (29 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"latencyMarkerSkip"
		},
	{ ATF_POINTER, 7, offsetof(struct Start, latencyPercentiles),
		(ASN_TAG_CLASS_CONTEXT | (30 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"latencyPercentiles"
		},
	{ ATF_POINTER, 6, offsetof(struct Start, messageMarker),
		(ASN_TAG_CLASS_CONTEXT | (31 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageMarker"
		},
	{ ATF_POINTER, 5, offsetof(struct Start, statsd),
		(ASN_TAG_CLASS_CONTEXT | (32 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statsd"
		},
	{ ATF_POINTER, 4, offsetof(struct Start, statsdHost),
		(ASN_TAG_CLASS_CONTEXT | (33 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statsdHost"
		},
	{ ATF_POINTER, 3, offsetof(struct Start, statsdPort),
		(ASN_TAG_CLASS_CONTEXT | (34 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TcpPort,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statsdPort"
		},
	{ ATF_POINTER, 2, offsetof(struct Start, statsdNamespace),
		(ASN_TAG_CLASS_CONTEXT | (35 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PrintableString,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statsdNamespace"
		},
	{ ATF_POINTER, 1, offsetof(struct Start, statsdLatencyWindow),
		(ASN_TAG_CLASS_CONTEXT | (36 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PositiveInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"statsdLatencyWindow"
		},
};
static const int asn_MAP_Start_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36 };
static const ber_tlv_tag_t asn_DEF_Start_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Start_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* target */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* nagle */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* rcvbuf */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* sndbuf */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* writeCombine */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* workers */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ws */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* ssl */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 }, /* sslCert */
    { (ASN_TAG_CLASS_CONTEXT | (9 << 2)), 9, 0, 0 }, /* sslKey */
    { (ASN_TAG_CLASS_CONTEXT | (10 << 2)), 10, 0, 0 }, /* header */
    { (ASN_TAG_CLASS_CONTEXT | (11 << 2)), 11, 0, 0 }, /* connections */
    { (ASN_TAG_CLASS_CONTEXT | (12 << 2)), 12, 0, 0 }, /* connectRate */
    { (ASN_TAG_CLASS_CONTEXT | (13 << 2)), 13, 0, 0 }, /* connectTimeout */
    { (ASN_TAG_CLASS_CONTEXT | (14 << 2)), 14, 0, 0 }, /* channelLifetime */
    { (ASN_TAG_CLASS_CONTEXT | (15 << 2)), 15, 0, 0 }, /* channelBandwidthUpstream */
    { (ASN_TAG_CLASS_CONTEXT | (16 << 2)), 16, 0, 0 }, /* channelBandwidthDownstream */
    { (ASN_TAG_CLASS_CONTEXT | (17 << 2)), 17, 0, 0 }, /* listenPort */
    { (ASN_TAG_CLASS_CONTEXT | (18 << 2)), 18, 0, 0 }, /* listenMode */
    { (ASN_TAG_CLASS_CONTEXT | (19 << 2)), 19, 0, 0 }, /* duration */
    { (ASN_TAG_CLASS_CONTEXT | (20 << 2)), 20, 0, 0 }, /* delaySend */
    { (ASN_TAG_CLASS_CONTEXT | (21 << 2)), 21, 0, 0 }, /* firstMessage */
    { (ASN_TAG_CLASS_CONTEXT | (22 << 2)), 22, 0, 0 }, /* message */
    { (ASN_TAG_CLASS_CONTEXT | (23 << 2)), 23, 0, 0 }, /* messageFile */
    { (ASN_TAG_CLASS_CONTEXT | (24 << 2)), 24, 0, 0 }, /* messageRate */
    { (ASN_TAG_CLASS_CONTEXT | (25 << 2)), 25, 0, 0 }, /* messageStop */
    { (ASN_TAG_CLASS_CONTEXT | (26 << 2)), 26, 0, 0 }, /* latencyConnect */
    { (ASN_TAG_CLASS_CONTEXT | (27 << 2)), 27, 0, 0 }, /* latencyFirstByte */
    { (ASN_TAG_CLASS_CONTEXT | (28 << 2)), 28, 0, 0 }, /* latencyMarker */
    { (ASN_TAG_CLASS_CONTEXT | (29 << 2)), 29, 0, 0 }, /* latencyMarkerSkip */
    { (ASN_TAG_CLASS_CONTEXT | (30 << 2)), 30, 0, 0 }, /* latencyPercentiles */
    { (ASN_TAG_CLASS_CONTEXT | (31 << 2)), 31, 0, 0 }, /* messageMarker */
    { (ASN_TAG_CLASS_CONTEXT | (32 << 2)), 32, 0, 0 }, /* statsd */
    { (ASN_TAG_CLASS_CONTEXT | (33 << 2)), 33, 0, 0 }, /* statsdHost */
    { (ASN_TAG_CLASS_CONTEXT | (34 << 2)), 34, 0, 0 }, /* statsdPort */
    { (ASN_TAG_CLASS_CONTEXT | (35 << 2)), 35, 0, 0 }, /* statsdNamespace */
    { (ASN_TAG_CLASS_CONTEXT | (36 << 2)), 36, 0, 0 } /* statsdLatencyWindow */
};
asn_SEQUENCE_specifics_t asn_SPC_Start_specs_1 = {
	sizeof(struct Start),
	offsetof(struct Start, _asn_ctx),
	asn_MAP_Start_tag2el_1,
	37,	/* Count of tags in the map */
	asn_MAP_Start_oms_1,	/* Optional members */
	37, 0,	/* Root/Additions */
	37,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_Start = {
	"Start",
	"Start",
	&asn_OP_SEQUENCE,
	asn_DEF_Start_tags_1,
	sizeof(asn_DEF_Start_tags_1)
		/sizeof(asn_DEF_Start_tags_1[0]), /* 1 */
	asn_DEF_Start_tags_1,	/* Same as above */
	sizeof(asn_DEF_Start_tags_1)
		/sizeof(asn_DEF_Start_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Start_1,
	37,	/* Elements count */
	&asn_SPC_Start_specs_1	/* Additional specs */
};

