/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#ifndef	_Stop_H_
#define	_Stop_H_


#include <asn_application.h>

/* Including external dependencies */
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Stop */
typedef struct Stop {
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Stop_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Stop;
extern asn_SEQUENCE_specifics_t asn_SPC_Stop_specs_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Stop_H_ */
#include <asn_internal.h>
