/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#include "TcpkaliMessage.h"

static int
setRate_6_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	if(1 /* No applicable constraints whatsoever */) {
		/* Nothing is here. See below */
	}
	
	return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using SetRate,
 * so here we adjust the DEF accordingly.
 */
static asn_oer_constraints_t asn_OER_type_setRate_constr_6 CC_NOTUSED = {
	{ sizeof(float), 0 },
	-1};
static asn_per_constraints_t asn_PER_type_setRate_constr_6 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_TcpkaliMessage_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_TcpkaliMessage_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  5 }	/* (0..5,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_NativeReal_specifics_t asn_SPC_setRate_specs_6 = {
	4	/* Use 'float' type. */
};
static const ber_tlv_tag_t asn_DEF_setRate_tags_6[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (9 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_setRate_6 = {
	"setRate",
	"setRate",
	&asn_OP_NativeReal,
	asn_DEF_setRate_tags_6,
	sizeof(asn_DEF_setRate_tags_6)
		/sizeof(asn_DEF_setRate_tags_6[0]) - 1, /* 1 */
	asn_DEF_setRate_tags_6,	/* Same as above */
	sizeof(asn_DEF_setRate_tags_6)
		/sizeof(asn_DEF_setRate_tags_6[0]), /* 2 */
	{ &asn_OER_type_setRate_constr_6, &asn_PER_type_setRate_constr_6, setRate_6_constraint },
	0, 0,	/* No members */
	&asn_SPC_setRate_specs_6	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_TcpkaliMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.start),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Start,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"start"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.stop),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Stop,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"stop"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.increaseRatePercent),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncreaseRatePercent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"increaseRatePercent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.decreaseRatePercent),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DecreaseRatePercent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"decreaseRatePercent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.setRate),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SetRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setRate"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.currentRate),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_CurrentRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"currentRate"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TcpkaliMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* start */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* stop */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* increaseRatePercent */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* decreaseRatePercent */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* setRate */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* currentRate */
};
static asn_CHOICE_specifics_t asn_SPC_TcpkaliMessage_specs_1 = {
	sizeof(struct TcpkaliMessage),
	offsetof(struct TcpkaliMessage, _asn_ctx),
	offsetof(struct TcpkaliMessage, present),
	sizeof(((struct TcpkaliMessage *)0)->present),
	asn_MAP_TcpkaliMessage_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0,
	6	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TcpkaliMessage = {
	"TcpkaliMessage",
	"TcpkaliMessage",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TcpkaliMessage_constr_1, &asn_PER_type_TcpkaliMessage_constr_1, CHOICE_constraint },
	asn_MBR_TcpkaliMessage_1,
	6,	/* Elements count */
	&asn_SPC_TcpkaliMessage_specs_1	/* Additional specs */
};

