/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "tcpkali_orchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#include "TcpkaliMessage.h"

static asn_oer_constraints_t asn_OER_type_TcpkaliMessage_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_TcpkaliMessage_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_TcpkaliMessage_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.increaseRatePercent),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_IncreaseRatePercent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"increaseRatePercent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.decreaseRatePercent),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_DecreaseRatePercent,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"decreaseRatePercent"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TcpkaliMessage, choice.setRate),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_SetRate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"setRate"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TcpkaliMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* increaseRatePercent */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* decreaseRatePercent */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* setRate */
};
static asn_CHOICE_specifics_t asn_SPC_TcpkaliMessage_specs_1 = {
	sizeof(struct TcpkaliMessage),
	offsetof(struct TcpkaliMessage, _asn_ctx),
	offsetof(struct TcpkaliMessage, present),
	sizeof(((struct TcpkaliMessage *)0)->present),
	asn_MAP_TcpkaliMessage_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TcpkaliMessage = {
	"TcpkaliMessage",
	"TcpkaliMessage",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_TcpkaliMessage_constr_1, &asn_PER_type_TcpkaliMessage_constr_1, CHOICE_constraint },
	asn_MBR_TcpkaliMessage_1,
	3,	/* Elements count */
	&asn_SPC_TcpkaliMessage_specs_1	/* Additional specs */
};

