/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#ifndef	_TcpPort_H_
#define	_TcpPort_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TcpPort */
typedef long	 TcpPort_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_TcpPort_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_TcpPort;
asn_struct_free_f TcpPort_free;
asn_struct_print_f TcpPort_print;
asn_constr_check_f TcpPort_constraint;
ber_type_decoder_f TcpPort_decode_ber;
der_type_encoder_f TcpPort_encode_der;
xer_type_decoder_f TcpPort_decode_xer;
xer_type_encoder_f TcpPort_encode_xer;
oer_type_decoder_f TcpPort_decode_oer;
oer_type_encoder_f TcpPort_encode_oer;
per_type_decoder_f TcpPort_decode_uper;
per_type_encoder_f TcpPort_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _TcpPort_H_ */
#include <asn_internal.h>
