/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#ifndef	_URL_H_
#define	_URL_H_


#include <asn_application.h>

/* Including external dependencies */
#include <PrintableString.h>

#ifdef __cplusplus
extern "C" {
#endif

/* URL */
typedef PrintableString_t	 URL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_URL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_URL;
asn_struct_free_f URL_free;
asn_struct_print_f URL_print;
asn_constr_check_f URL_constraint;
ber_type_decoder_f URL_decode_ber;
der_type_encoder_f URL_encode_der;
xer_type_decoder_f URL_decode_xer;
xer_type_encoder_f URL_encode_xer;
oer_type_decoder_f URL_decode_oer;
oer_type_encoder_f URL_encode_oer;
per_type_decoder_f URL_decode_uper;
per_type_encoder_f URL_encode_uper;

#ifdef __cplusplus
}
#endif

#endif	/* _URL_H_ */
#include <asn_internal.h>
