/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TcpkaliOrchestration"
 * 	found in "TcpkaliOrchestration.asn1"
 * 	`asn1c -gen-OER -gen-PER -pdu=TcpkaliMessage`
 */

#include "URL.h"

/*
 * This type is implemented using PrintableString,
 * so here we adjust the DEF accordingly.
 */
asn_per_constraints_t asn_PER_type_URL_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  32,  122 }	/* (32..122) */,
	{ APC_SEMI_CONSTRAINED,	-1, -1,  0,  0 }	/* (SIZE(0..MAX)) */,
	0, 0	/* No PER character map necessary */
};
static const ber_tlv_tag_t asn_DEF_URL_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (19 << 2))
};
asn_TYPE_descriptor_t asn_DEF_URL = {
	"URL",
	"URL",
	&asn_OP_PrintableString,
	asn_DEF_URL_tags_1,
	sizeof(asn_DEF_URL_tags_1)
		/sizeof(asn_DEF_URL_tags_1[0]), /* 1 */
	asn_DEF_URL_tags_1,	/* Same as above */
	sizeof(asn_DEF_URL_tags_1)
		/sizeof(asn_DEF_URL_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_URL_constr_1, PrintableString_constraint },
	0, 0,	/* No members */
	0	/* No specifics */
};

